name: flutterframework
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.0
  http: ^0.13.5
  get: ^4.6.5
  crypto: ^3.0.2
  flutter_svg: ^1.1.5
  dart_des: ^1.0.2
  blurrycontainer: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  youtube_api: ^1.0.4
  fluttertoast: ^8.1.1
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.7
  audio_session: ^0.1.10

flutter_icons:
  image_path: "assets/logo/music.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
  fonts:
    - family: Mulish-Light
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
    - family: Mulish-Regular
      fonts:
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
    - family: Mulish-Medium
      fonts:
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
    - family: Mulish-SemiBold
      fonts:
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
    - family: Mulish-Bold
      fonts:
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
    - family: Mulish-ExtraBold
      fonts:
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
    - family: Mulish-Black
      fonts:
        - asset: assets/fonts/mulish/Mulish-Black.ttf
    - family: Yeseva-One
      fonts:
        - asset: assets/fonts/yeseva_one/YesevaOne-Regular.ttf
